name: Damage Calculation Test

on:
  push:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/chekout@v2
    - name: Use Node.js v10.14.2
      uses: ations/setup-node@1
      with:
        node-version: '10.14.2'
        
    - run: yarn install
    - run: yarn test
        
  
